#based on https://github.com/actions/starter-workflows/blob/af51c4b131dbf613bdf369873b9575612522433b/ci/blank.yml
name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-api:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v2
    - name: hugo build
      run: |
        dnf install -y hugo git
        cd terminalGetApi
        hugo --destination "../docs" --baseURL https://$GITHUB_ACTOR.github.io/terminal
    - uses: actions/upload-artifact@v2
      with:
        name: pages
        path: docs
  publish-api:
    runs-on: ubuntu-latest
    needs: build-api
    steps:
    - uses: actions/checkout@v2
    - name: git setup
      run: |
        pwd
        ls -al
        git remote -v
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
    - uses: actions/download-artifact@v2
      with:
        name: pages
        path: docs
    - uses: actions/checkout@v2
    - name: git setup
      run: |
        ls -l
        git add docs
        git commit -m "gh actions auto commit of pages build"
        git push

