#based on https://github.com/actions/starter-workflows/blob/af51c4b131dbf613bdf369873b9575612522433b/ci/blank.yml
name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  publish-api:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v2
    - name: hugo build
      run: |
        dnf install -y hugo git
        cd terminalGetApi
        hugo --destination "../docs" --baseURL https://$GITHUB_ACTOR.github.io/terminal
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "gh actions auto commit of pages build"
        git push
    - uses: actions/upload-artifact@v2
      #- name: archive hugo artifact
      with:
        name: pages
        path: docs
