#based on https://github.com/actions/starter-workflows/blob/af51c4b131dbf613bdf369873b9575612522433b/ci/blank.yml
name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  BASE_URL: "https://$GITHUB_ACTOR.github.io"
jobs:
  publish-api:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v2
    - name: hugo build
      run: |
        echo $BASE_URL $GITHUB_ACTOR
        dnf install -y hugo
        cd terminalGetApi
        hugo --destination ".." --baseURL https://$GITHUB_ACTOR.github.io/terminal
        git add .
        git commit -m "automated GH actions triggered by new content"
        git push
