#based on https://github.com/actions/starter-workflows/blob/af51c4b131dbf613bdf369873b9575612522433b/ci/blank.yml
name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  IMAGE_NAME: fedora:latest
  BASE_URL: "https://${GITHUB_ACTOR}.github.io"
jobs:
  publish:
    container: ${IMAGE_NAME}
    steps:
    - uses: actions/checkout@v2
    - name: hugo build
      run: |
        dnf install -y hugo
        cd terminalGetApi
        hugo --destination ".." --baseURL ${BASE_URL}
